addons:
  sauce_connect: true
language: node_js
before_script:
  - wget -O bin/or1k/vmlinux.bin.bz2 https://dugoh.github.io/tcb/vmlinux.bin.bz2
  - python -m SimpleHTTPServer &
  - sleep 2
node_js:
  - '7.4'
after_script:
  - rm -rf ./.git
  - git init
  - git config user.name "${USER}"
  - git config user.email "${GH_MAIL}"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - printf "${USER}\n${GH_MAIL}\n${TRAVIS_REPO_SLUG}\n"
  - printf "${GH_TOKEN}\n"|cut -b 1
  - set|egrep -i "dugo|jacob"
  - git push --force --quiet https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master:gh-pages #>/dev/null 2>&1
